// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pagination.Data;

namespace Pagination.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220223040106_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pagination.Data.Demo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Demo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chan Sin Yow"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Yong Han"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Amelia"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Amy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Angela"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Anna"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Anne"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Bella"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Belle"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Carol"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Chloe"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Claire"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Diana"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Ella"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Emily"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Emma"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Sam"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Tony Stark"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Peter Parker"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Steve"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Steve"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Steve"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Steve"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Steve"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Steve"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Sos"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Sos"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Sos"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Sos"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Sos"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Covid"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Covid"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Covid"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Covid"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Covid"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Covid"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
